spring:
  activemq:
    broker-url: failover:(tcp://activemq-dev-0.activemq-dev-headless.dev.svc.cluster.local:61616?daemon=true&keepAlive=true)?randomize=true&jms.useAsyncSend=false
    in-memory: true
    pool:
      enabled: false
      max-connections: 20
    packages:
      trust-all: true

framework:
  enabled: true
  zookeeper:
    default:
      connect-string: zookeeper-dev.dev.svc.cluster.local:2181
      timeout: 5000
      config-path: /xxt/config
      pubsub-path: /xxt/pubsub
  redis:
    default:
      name: default
      type: SHARD
      nodes:
        - host: redis-dev-0.redis-dev-headless.dev.svc.cluster.local
          port: 6379
  elasticsearch:
    default:
      nodes:
        - host: xh-es-master-0.xh-es-master-headless.prod.svc.cluster.local
          port: 9200
        - host: xh-es-master-1.xh-es-master-headless.prod.svc.cluster.local
          port: 9200
        - host: xh-es-master-2.xh-es-master-headless.prod.svc.cluster.local
          port: 9200
      username: xihang
      password: sHo1f4Ngu2cQO3VAXmYV
  rocketmq:
    config:
      nameSvr: statefulset-rocketmq-namesrv-dev-0.service-rocketmq-namesrv-dev:9876
  mvc:
    cors:
      allowed-origins:
        - "*"
  sentinel:
    transport:
      dashboard: sentinel-dashboard-dev-java-app.dev.svc.cluster.local:8080

dubbo:
  application:
    logger: log4j2
  protocol:
    name: dubbo
    port: 5000
  config-center:
    address: zookeeper://zookeeper-dev.dev.svc.cluster.local:2181
  registry:
    address: zookeeper://zookeeper-dev.dev.svc.cluster.local:2181