server:
  port: 8089
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto

spring:
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    jackson:
      default-property-inclusion: non_null
      serialization:
        FAIL_ON_EMPTY_BEANS: false
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
  jackson:
    default-property-inclusion: non_null
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    initialize: false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 300
      #driver-class-name:
      #minimum-idle: 1
      connection-timeout: 3000
      idle-timeout: 60000
      #max-lifetime: 1800000
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration,
      org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration,
      org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration,
      org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration,
      org.springframework.boot.autoconfigure.couchbase.CouchbaseAutoConfiguration,
      org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration,
      org.springframework.boot.autoconfigure.data.cassandra.CassandraRepositoriesAutoConfiguration,
      org.springframework.boot.autoconfigure.data.couchbase.CouchbaseDataAutoConfiguration,
      org.springframework.boot.autoconfigure.data.couchbase.CouchbaseRepositoriesAutoConfiguration,
      org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration,
      org.springframework.boot.autoconfigure.data.ldap.LdapDataAutoConfiguration,
      org.springframework.boot.autoconfigure.elasticsearch.jest.JestAutoConfiguration,
      org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration,
      org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration,
      org.springframework.boot.autoconfigure.jms.artemis.ArtemisAutoConfiguration,
      org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration,
      org.springframework.boot.autoconfigure.security.SecurityFilterAutoConfiguration,
      org.springframework.boot.autoconfigure.security.FallbackWebSecurityAutoConfiguration,
      org.springframework.boot.autoconfigure.security.oauth2.OAuth2AutoConfiguration,
      org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration,
      org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration

mybatis:
  configuration:
    map-underscore-to-camel-case: true

management:
  security:
    enabled: false

endpoints:
  enabled: false
  trace:
    filter:
      enabled: false
  env:
    post:
      enabled: false


