spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-dev.dev.svc.cluster.local:3306/partner_training?useOldAliasMetadataBehavior=true
    username: dev
    password: xxtmysql110

dubbo:
  application:
    logger: log4j2
  protocol:
    name: dubbo
    port: 10002
  config-center:
    address: zookeeper://zookeeper-dev.dev.svc.cluster.local:2181
  registry:
    address: zookeeper://zookeeper-dev.dev.svc.cluster.local:2181

server:
  port: 10012
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto

framework:
  enabled: true
  zookeeper:
    default:
      connect-string: zookeeper-dev.dev.svc.cluster.local:2181
      timeout: 5000
      config-path: /xxt/config
      pubsub-path: /xxt/pubsub
  redis:
    default:
      name: default
      type: SHARD
      nodes:
        - host: redis-dev-0.redis-dev-headless.dev.svc.cluster.local
          port: 6379