server:
  port: 8082
spring:
  application:
    name: demo_consumer
  profiles:
    group:
      "dev": "common,common-dev"
      "prod": "common,common-prod"

dubbo:
  scan:
    base-packages: org.example.dubbo


